# paths to ignore
excluded:
  - Carthage
  - Pods
  - Guides
  - fastlane
  - vendor
  - docs
  - scripts

disabled_rules:
  - identifier_name
  - nesting
  - type_name
  - trailing_comma
  - void_return

opt_in_rules:
  # performance
  - empty_count
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil

  # idiomatic
  - fatal_error_message

  # style
  - number_separator
  - operator_usage_whitespace
  - sorted_imports

  # lint
  - overridden_super_call

file_length: 650
line_length: 200

type_body_length: 400

function_body_length: 150
